### ISSUE TITLE
Support Custom Directory / Portable Mode

### ISSUE THREAD

**Issue by NoPlagiarism** [AminSallah/Flow.Launcher.Plugin.WinHotkey#3]

**Comment by AminSallah** [comment]
I haven't used portable version before. Does it store Settings.json somewhere else instead of in AppData?

**Comment by NoPlagiarism** [comment]
In my Scoop version it's `app-1.17.2\UserData`

Here's code with function that returns if `PortableDataLocationInUse`, and also there's function that returns active UserData path

https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/Flow.Launcher.Infrastructure/UserSettings/DataLocation.cs

And here's the code of System Plugin for reference

https://github.com/Flow-Launcher/Flow.Launcher/blob/7d171a39133ae9ae1d5804009d1988d80f7d117b/Plugins/Flow.Launcher.Plugin.Sys/Main.cs#L407L417

Hope it helps

**Comment by AminSallah** [comment]
Thank you for reporting this issue and your well described message. WinHotkey v3.1.0 should now work smoothly with portable versions. If plugin update didn't show up in plugin store you can access it by paste this in FL query `pm install https://github.com/AminSallah/Flow.Launcher.Plugin.WinHotkey/releases/download/v3.1.0/Flow.Launcher.Plugin.WinHotkey.zip`  Let me know if this fixed the issue with your version.

**Comment by NoPlagiarism** [comment]
Yeah after https://github.com/AminSallah/Flow.Launcher.Plugin.WinHotkey/commit/582647e9a904ba91f229140e9ff39fd5be8b3355, works fine. Thanks for your work

Still gonna wait 2 hours till https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest updates
