### ISSUE TITLE
WinHotkey doesn't work when an application running with administrtor previlage is in focus.

### ISSUE THREAD

**Issue by Bits-Bytes-354** [AminSallah/Flow.Launcher.Plugin.WinHotkey#7]
WinHotkey doesn't work when an application running with administrtor previlage is in focus. When 'Win' key is pressed in such situation start menu pops up instead of Flow Launcher.

**_How to re-create the issue_**: You can test it by running 2 instance of same application one with administrator previlage and one with normal previlage, now press 'Win' key by focusing on both the application once at a time. But when start menu is poped up pressing 'Win' key again will not close the start mneu but show flow launcher behind the start menu.

**_Results_**: with focus on instance with administrator previlage start menu will pop up and when the focus in on the instance with normal previlage flow launcher will pop up.

**Comment by AminSallah** [comment]
This could be due to the security restrictions imposed by Windows User Account Control (UAC). Currently, there is no way for the plugin to capture key presses on a process that runs with elevated privileges than its own. To resolve this issue, try running FL with higher privileges as an administrator.

**Comment by Bits-Bytes-354** [comment]
Thanks for the solution.

**Comment by Bits-Bytes-354** [comment]
I think it will be best if you are able to specify it in the WinHotKey configuration page. 

I have configured to always run flow launcher as administrator at logon and the plugin is working flawlessly, extremely happy with it. Thanks once again for creating such plugin. 😄

**Comment by AminSallah** [comment]
> I think it will be best if you are able to specify it in the WinHotKey configuration page.

Unfortunately, this is not possible because the main plugin method is not an executable file and does not run in a separate process. it runs within the main Flow Launcher process.
