### ISSUE TITLE
Start Menu shows on top of Flow Launcher

### ISSUE THREAD

**Issue by tk397** [AminSallah/Flow.Launcher.Plugin.WinHotkey#8]
Hi, 

When using LWin key to launch FL, it works, but sometimes when I press the button a little too long it opens Start Menu (expected), then when LWin is short pressed after that it opens Flow underneath the Start Menu without closing it.

![image](https://github.com/AminSallah/Flow.Launcher.Plugin.WinHotkey/assets/7893222/8af28020-a67c-421f-baa4-ce76daa52a5b)

System:
Win 11
Flow Launcher + WinHotkey

Thanks!

**Comment by AminSallah** [comment]
Hey @TarikHKj,

Thanks for your request. The issue raised involves the blinding mechanism that the plugin uses to prevent windows from capturing the Windows key press. This causes the focus to remain on any taskbar element, even if Flow Launcher is triggered. In the new version, taskbar elements like the Start menu and notification panel should be closed manually to prevent this issue. I can guarantee this functionality in Windows 10 but not in Windows 11. You can build the plugin and test it; currently, there are no releases scheduled as the plugin aims to adopt more customizability by using other modifiers such as Ctrl and Alt to trigger Flow Launcher.

Let me know if the new version works on your OS. If it doesn't work on Windows 11, please reopen a new issue focusing only on the Windows 11 issue.
